name: country_state_picker_plus
description: Country state picker
version: 1.0.0+1
homepage: https://github.com/kishanSindhi
repository: https://github.com/kishanSindhi/country_state_picker_plus

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/country.json
